name: "suite-ai"

services:
  chainprompt-ai-collaudo:
    image: chainprompt-ai-collaudo:${IMG_VERSION:-latest}
    container_name: chainprompt-ai-collaudo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5500:5000"
      - "127.0.0.1:6000:6000"      
    env_file:
      - ./.env.collaudo
    networks:
      - network-chainprompt-docker
    volumes:
      #le conversazioni sono gestite da redis e non piu su file system
      #- ./src/datasets/conversations:/app/datasets/conversations
      - ./:/usr/app
      - /usr/app/node_modules      
    entrypoint: ./entry-point.sh 

  chainprompt-plugins:
    image: chainprompt-plugins:${IMG_VERSION:-latest}
    container_name: chainprompt-plugins-collaudo
    build:
      context: ./
      dockerfile: Dockerfile.plugins
    ports:
      - "127.0.0.1:5600:80"
    networks:
      - network-chainprompt-docker      
    volumes:
      # Monta la cartella plugins locale nel container in modo da poter aggiornare i plugin in tempo reale
      - ./plugins:/usr/share/nginx/html/plugins
    restart: always

networks:
  network-chainprompt-docker:
    driver: bridge