name: "suite-ai-local"

services:
  chainprompt-ai:
    image: chainprompt-ai-local:${IMG_VERSION:-latest}
    container_name: chainprompt-ai-local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5500:5000"
      - "9339:9229"
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME:-chainprompt}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-!!!Chainprompt!!!}      
    env_file:
      - ./.env.dev
    networks:
      - network-chainprompt
      #usato per test interni accedendo a ollama passando per la rete docker
      - aiassistant_ollama_network        
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules      
    entrypoint: ./entry-point.sh 

  chainprompt-plugins:
    image: chainprompt-plugins-local:${IMG_VERSION:-latest}
    container_name: chainprompt-plugins-local
    build:
      context: ./
      dockerfile: Dockerfile.plugins
    ports:
      - "5510:80"
    networks:
      - network-chainprompt
    volumes:
      # Monta la cartella plugins locale nel container in modo da poter aggiornare i plugin in tempo reale
      - ./plugins:/usr/share/nginx/html/plugins
    restart: always

networks:
  network-chainprompt:
    external: true
    driver: bridge

  aiassistant_ollama_network:
    external: true    